server:
  port: 8081

resources:
  image:
    location: /home/habikery/resources/images/
    url: 49.50.167.14/resources/images
  categories:
    - id: 1
      habit-type: WATER
      cake-type: WATERMELON
      cakeDescription: "물 마시는 나에게"
      diaryDescription: "수분충전"
    - id: 2
      habit-type: STRETCHING
      cake-type: CHEESE
      cakeDescription: "스트레칭하는 나에게"
      diaryDescription: "쭉쭉 늘어나는"
    - id: 3
      habit-type: MEDITATION
      cake-type: WHIPPING_CREAM
      cakeDescription: "명상하는 나에게"
      diaryDescription: "부드러운 마음"
    - id: 4
      habit-type: WALK
      cake-type: GREEN_TEA
      cakeDescription: "산책하는 나에게"
      diaryDescription: "싱그러운"
    - id: 5
      habit-type: NEWS
      cake-type: COFFEE
      cakeDescription: "뉴스보는 나에게"
      diaryDescription: "아침을 깨우는"
    - id: 6
      habit-type: BREAKFAST
      cake-type: APPLE
      cakeDescription: "아침먹는 나에게"
      diaryDescription: "하루의 시작"
    - id: 7
      habit-type: DIARY
      cake-type: CHESTNUT
      cakeDescription: "일기쓰는 나에게"
      diaryDescription: "나를 위한 시간"
    - id: 8
      habit-type: READING
      cake-type: WALNUT
      cakeDescription: "책읽는 나에게"
      diaryDescription: "마음의 양식"

spring:
  profiles:
    active: develop
---
spring:
  profiles: develop
  datasource:
    url: jdbc:postgresql://localhost:5432/habikery
    username: moss
    password: habikery
    platform: postgres
    hikari:
      auto-commit: false
      idle-timeout: 10000
      minimumIdle: 30
      maximum-pool-size: 150
      read-only: false
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false

    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
---
spring:
  profiles: test
  datasource:
    test:
      jdbc-url: jdbc:h2:mem:habikery
      username: sa
      password:
      driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console
---