

server:
  port: 8081

resources:
  image:
    location: /home/habikery/resources/images/
    url: 49.50.167.14/resources/images
  categories:
    - id: 1
      habit-type: WATER
      cake-type: WATERMELON
    - id: 2
      habit-type: STRETCHING
      cake-type: CHEESE
    - id: 3
      habit-type: MEDITATION
      cake-type: WHIPPING_CREAM
    - id: 4
      habit-type: WALK
      cake-type: GREEN_TEA
    - id: 5
      habit-type: NEWS
      cake-type: COFFEE
    - id: 6
      habit-type: BREAKFAST
      cake-type: APPLE
    - id: 7
      habit-type: DIARY
      cake-type: CHESTNUT
    - id: 8
      habit-type: READING
      cake-type: WALNUT

spring:
  profiles:
    active: develop
---
spring:
  profiles: develop
  datasource:
    url: jdbc:postgresql://localhost:5432/habikery
    username: moss
    password: habikery
    platform: postgres
    hikari:
      auto-commit: false
      idle-timeout: 10000
      minimumIdle: 30
      maximum-pool-size: 150
      read-only: false
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false

    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
---
spring:
  profiles: test
  datasource:
    test:
      jdbc-url: jdbc:h2:mem:habikery
      username: sa
      password:
      driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console
---