version: '3'
services:
  nginx:
    container_name: habikery-nginx
    image: nginx:1.14
    restart: always
    ports:
      - 80:80
#      - 443:443
    volumes:
      - /home/habikery/nginx:/etc/nginx
    networks:
      - back
    depends_on:
      - habikery-api
  postgresql:
    container_name: habikery-postgres
    image: postgres:11.2-alpine
    volumes:
      - /home/habikery/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: habikery
      POSTGRES_USER: moss
      POSTGRES_DB: habikery
    ports:
      - "5432:5432"
    networks:
      - back
    restart: always

  habikery-api:
    container_name: habikery-api
    image: habikery/moss:latest
    volumes:
      - /home/habikery/resources:/home/habikery/resources # image path
      - ./config:/config # config path
    entrypoint:
      - java
      - -jar
      - -Dspring.config.location=./config/application.yaml
      - -Dspring.profiles.active=develop
      - habikery-api.jar
    depends_on:
      - postgresql
    networks:
      - back
    restart: always

networks:
  back:
    driver: bridge