version: '3'
services:
  postgresql:
    container_name: habikery-postgres
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: habikery
      POSTGRES_USER: moss
      POSTGRES_DB: habikery
    ports:
      - "5432:5432"
    restart: always